# Generated by Django 3.2.9 on 2021-11-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0002_auto_20211129_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
