# Generated by Django 3.2.9 on 2021-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0003_rename_status_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_surname',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_telno',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
