# Generated by Django 3.2.9 on 2021-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0004_auto_20211129_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
