# Generated by Django 3.2.9 on 2021-11-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0005_alter_order_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_order.orderstatus'),
        ),
    ]
