# Generated by Django 3.2.9 on 2021-12-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0009_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api_order.paymenttype'),
            preserve_default=False,
        ),
    ]
