# Generated by Django 3.2.9 on 2021-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0011_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_telno',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
