# Generated by Django 3.2.9 on 2021-12-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0012_alter_order_to_telno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api_order.paymenttype'),
            preserve_default=False,
        ),
    ]
