# Generated by Django 4.0.2 on 2022-03-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_characteristic_alter_orderstatus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristic',
            old_name='characteristics',
            new_name='characteristic',
        ),
    ]
