# Generated by Django 3.2.9 on 2022-02-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bird'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bird',
        ),
    ]
