# Generated by Django 4.0.2 on 2022-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productcharacteristic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='data', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(db_index=True, default='emil.nadzhiev@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(db_index=True, default=380506793306, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='postal_code',
            field=models.CharField(db_index=True, default=385415, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
