# Generated by Django 4.0.2 on 2022-02-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_bird'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
        migrations.AlterModelTable(
            name='productprice',
            table='product_price',
        ),
    ]
