# Generated by Django 4.0.2 on 2022-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_table_alter_productprice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product/default_product.png', upload_to='product'),
        ),
    ]
