# Generated by Django 4.0.2 on 2022-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
