# Generated by Django 4.0.2 on 2022-02-06 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productprice_date_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
