# Generated by Django 4.0.2 on 2022-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0012_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
