# Generated by Django 4.0.2 on 2022-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
