# Generated by Django 4.0.2 on 2022-05-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_review_product_reviews_review_product_review_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
