# Generated by Django 4.0.2 on 2022-02-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cartitem_orderstatus_paymenttype_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'order')},
        ),
    ]
