# Generated by Django 4.0.2 on 2022-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
