# Generated by Django 4.0.2 on 2022-02-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_patronymic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_surname',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=45, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(max_length=45, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=45, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.paymenttype', verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='store.orderstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.vendor', verbose_name='Производитель'),
        ),
    ]
