# Generated by Django 4.0.2 on 2022-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Электронная почта'),
        ),
    ]
