# Generated by Django 4.0.2 on 2022-02-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store.vendor', verbose_name='Производитель'),
        ),
    ]
