# Generated by Django 3.2.9 on 2022-01-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'api_package',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(db_index=True, max_length=100)),
                ('endpoint_url', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'endpoint',
            },
        ),
        migrations.CreateModel(
            name='HttpMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'http_method',
            },
        ),
        migrations.CreateModel(
            name='EndpointMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_params', models.JSONField(default=dict)),
                ('out_params', models.JSONField(default=dict)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endpoint')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.httpmethod')),
            ],
            options={
                'db_table': 'endpoint_has_method',
                'unique_together': {('endpoint', 'method')},
            },
        ),
        migrations.AddField(
            model_name='endpoint',
            name='methods',
            field=models.ManyToManyField(related_name='endpoints', through='api.EndpointMethod', to='api.HttpMethod'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apipackage'),
        ),
    ]
