# Generated by Django 3.2.9 on 2022-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_url',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='package',
        ),
    ]
