# Generated by Django 3.2.9 on 2022-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220103_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndpointMethod',
        ),
    ]
