# Generated by Django 3.2.9 on 2022-01-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_endpointmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiPackage',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='HttpMethod',
        ),
    ]
