# Generated by Django 3.2.9 on 2021-11-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_product', '0021_alter_product_product_image'),
        ('api_order', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_product.product')),
            ],
        ),
    ]
