# Generated by Django 3.2.9 on 2021-11-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcart',
            table='shopping_cart',
        ),
    ]
