# Generated by Django 3.2.9 on 2021-11-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_shopping_cart', '0002_alter_shoppingcart_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='package',
            new_name='order',
        ),
    ]
