# Generated by Django 3.2.9 on 2021-11-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_shopping_cart', '0003_rename_package_shoppingcart_order'),
    ]

    operations = [
    ]
