# Generated by Django 3.2.9 on 2021-11-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_shopping_cart', '0005_procedures'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE PROCEDURE add_product_to_cart(prod_id int, usr_id int, n int)
            language plpgsql    
            as $$
                DECLARE ord_id INT;
                DECLARE dif INT;
            begin
                LOCK TABLE product IN SHARE MODE;
            
                SELECT id INTO ord_id FROM "order" WHERE user_id = usr_id AND order_status_id is NULL LIMIT 1;
                IF EXISTS(SELECT * FROM shopping_cart where product_id=prod_id AND order_id = ord_id) THEN
                    SELECT amount INTO dif FROM shopping_cart where product_id=prod_id AND order_id = ord_id;
                    UPDATE shopping_cart set amount = n where product_id=prod_id AND order_id = ord_id;
                    dif := dif - n;
                ELSE
                    INSERT INTO shopping_cart (product_id, order_id, amount) VALUES (prod_id, ord_id, n);
                    dif := -n;
                END IF;
                UPDATE product SET product_amount = product_amount + dif WHERE id = prod_id;
            
                IF NOT EXISTS(SELECT id FROM product WHERE id = prod_id AND product_amount>=0) THEN
                    RAISE EXCEPTION 'Товар % не может быть добавлен в корзину', prod_id;
                ELSIF NOT EXISTS(SELECT id FROM "order" WHERE id = ord_id AND order_status_id IS NULL) THEN
                    RAISE EXCEPTION 'Заказ % не является корзиной', ord_id;
                ELSE
                    commit;
                END IF;
            end;
            $$;
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE PROCEDURE del_product_from_cart(prod_id int, usr_id int)
            language plpgsql    
            as $$
                DECLARE ord_id INT;
                DECLARE amount_to_add INT;
            begin
                LOCK TABLE product IN SHARE MODE;

                SELECT id INTO ord_id FROM "order" WHERE user_id = usr_id AND order_status_id is NULL LIMIT 1;
                SELECT amount INTO amount_to_add FROM shopping_cart WHERE product_id = prod_id AND order_id = ord_id;
                DELETE FROM shopping_cart WHERE product_id = prod_id AND order_id = ord_id;
                UPDATE product SET product_amount = product_amount + amount_to_add WHERE id = prod_id;

                IF NOT EXISTS(SELECT id FROM "order" WHERE id = ord_id AND order_status_id IS NULL) THEN
                    ROLLBACK;
                ELSE
                    commit;
                END IF;
            end;
            $$;
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE PROCEDURE clear_cart(usr_id int)
            language plpgsql    
            as $$
                DECLARE ord_id INT;
                row RECORD;
            begin
                LOCK TABLE product IN SHARE MODE;

                SELECT id INTO ord_id FROM "order" WHERE user_id = usr_id AND order_status_id is NULL LIMIT 1;


                FOR row IN SELECT product_id, amount FROM shopping_cart WHERE order_id = ord_id LOOP
                DELETE FROM shopping_cart WHERE product_id = row.product_id AND order_id = ord_id;
                UPDATE product SET product_amount = product_amount + row.amount WHERE id = row.product_id;
                END LOOP;


                IF NOT EXISTS(SELECT id FROM "order" WHERE id = ord_id AND order_status_id IS NULL) THEN
                    ROLLBACK;
                ELSE
                    commit;
                END IF;
            end;
            $$;
        """)
    ]
