# Generated by Django 3.2.9 on 2021-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shopping_cart', '0006_create_procedures'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', '1')), name='amount_positive'),
        ),
    ]
