# Generated by Django 3.2.9 on 2021-11-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0024_product_product_price_non_negative'),
        ('api_shopping_cart', '0007_shoppingcart_amount_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_product.product'),
        ),
    ]
