# Generated by Django 4.0.2 on 2022-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', [1, 2])), name='valid_role'),
        ),
    ]
