# Generated by Django 4.0.2 on 2022-04-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
