# Generated by Django 3.2.9 on 2021-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0002_auto_20211106_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_characteristics',
            field=models.ManyToManyField(related_name='products', through='api_product.ProductCharacteristics', to='api_product.Characteristics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterUniqueTogether(
            name='characteristics',
            unique_together={('char_name', 'char_value')},
        ),
    ]
