# Generated by Django 3.2.9 on 2021-11-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_auto_20211106_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'characteristics_type',
            },
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='characteristics_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api_product.characteristicstype'),
            preserve_default=False,
        ),
    ]
