# Generated by Django 3.2.9 on 2021-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0005_remove_productcharacteristics_characteristics_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='characteristicstype',
            table='characteristics_typ',
        ),
    ]
