# Generated by Django 3.2.9 on 2021-11-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0006_alter_characteristicstype_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacteristicsType',
        ),
    ]
