# Generated by Django 3.2.9 on 2021-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0007_delete_characteristicstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'characteristics_type',
            },
        ),
    ]
