# Generated by Django 3.2.9 on 2021-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0009_delete_characteristicstype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together={('product', 'chars')},
        ),
    ]
