# Generated by Django 3.2.9 on 2021-11-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0010_alter_productcharacteristics_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristics',
            unique_together=set(),
        ),
    ]
