# Generated by Django 3.2.9 on 2021-11-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0011_alter_characteristics_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='char_value',
        ),
    ]
