# Generated by Django 3.2.9 on 2021-11-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0013_auto_20211107_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='chars',
            new_name='char',
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together={('product', 'char')},
        ),
    ]
