# Generated by Django 3.2.9 on 2021-11-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0014_auto_20211107_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='char',
            new_name='char_name',
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together={('product', 'char_name')},
        ),
    ]
