# Generated by Django 3.2.9 on 2021-11-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0015_auto_20211107_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcharacteristics',
            old_name='char_name',
            new_name='char',
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together={('product', 'char', 'char_value')},
        ),
    ]
