# Generated by Django 3.2.9 on 2021-11-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0018_auto_20211107_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='api_product.vendor'),
        ),
    ]
