# Generated by Django 3.2.9 on 2021-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0019_alter_product_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.png', upload_to='product'),
        ),
    ]
