# Generated by Django 3.2.9 on 2021-11-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0023_alter_product_product_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('product_price__gte', '0')), name='product_price_non_negative'),
        ),
    ]
